version: '2.1'
services:
  frontend:
    image: elastest/eds-frontend:latest
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 4000
      - 6065
      - 8000
    networks:
      - elastest

  memsipe:
    image: elastest/eds-memsipe:latest
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 5050
      - 8000
    links:
      - frontend
    networks:
      - elastest

  rest_app:
    image: elastest/eds-api:latest
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 8080
      - 9090
    links:
      - frontend
    networks:
      - elastest

  eds:
    image: elastest/eds:latest
    container_name: eds
    hostname: eds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    expose:
      - 16500
    ports:
      - "16500:16500"
    networks:
      - elastest

networks:
  elastest:
    driver: bridge
