version: '2'
services:
  frontend:
    image: elastest/eds-frontend:0.5.0
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 4000
      - 6065
      - 8000
    networks:
      - elastest_elastest

  memsipe:
    image: elastest/eds-memsipe:0.5.0
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 5050
    networks:
      - elastest_elastest

  zigbeeipe:
    image: elastest/eds-zigbeeipe:0.5.0
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 5001
    networks:
      - elastest_elastest

  rest_app:
    image: elastest/eds-api:0.5.0
    environment:
      - EDS_PORT=37010
      - ET_EMP_API=http://eim:37001/
      - ET_EDS_API=http://eim:37010/
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 37010
    ports:
     - 37010:37010
    networks:
      - elastest_elastest

networks:
  elastest_elastest:
    external: true
