version: '2'
services:
  frontend:
    image: elastest/eds-frontend:0.5.0
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 4000
      - 6065
      - 8000
    networks:
      - elastest_elastest

  memsipe:
    image: elastest/eds-memsipe:0.5.0
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 5050
    networks:
      - elastest_elastest

  zigbeeipe:
    image: elastest/eds-zigbeeipe:0.5.0
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 5001
    networks:
      - elastest_elastest

  rest_app:
    image: elastest/eds-api:0.5.0
    environment:
      - EDS_PORT=19089
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 19089
    ports:
     - 19089:19089
    networks:
      - elastest_elastest

networks:
  elastest_elastest:
    external: true
