version: '2'
services:
  zigbeeipe:
    image: elastest/eds-zigbeeipe:0.5.0-alpha1
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 5001
    networks:
      - elastest_elastest

  frontend:
    image: elastest/eds-frontend:0.5.0-alpha1
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 4000
      - 6065
      - 8000
    networks:
      - elastest_elastest

  memsipe:
    image: elastest/eds-memsipe:0.5.0-alpha1
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 5050
    networks:
      - elastest_elastest

  api:
    image: elastest/eds-gateway:0.5.0-alpha1
    environment:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
    expose:
      - 8080
    networks:
      - elastest_elastest

networks:
  elastest_elastest:
    external: true
