swagger: "2.0"

info:
  title: "{{title}}"
  version: "0.0.5"

basePath: /eds

paths:
  /devices:
    get:
      #operationId: api.devices.get
      parameters:
       - in: query
         name: name
         type: string
         enum: ["ZigBeeIPE", "MemsIPE"]
         description: "Enter sensor device name here."
         #required: true
       #- in: query
        # name: id
       #  type: string
        # enum: ["MEMS01", "ZBS122S000000"]
        # example: MEMS01
        # description: "Enter sensor device ID here."
         #required: true
      responses:
        '200':
          description: 'Fetch a list of devices'
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
    post:
      #operationId: api.devices.post
      parameters:
        - in: body
          name: name
          required: true
          schema:
            $ref: '#/definitions/Device'
      responses:
        '201':
          description: 'List of device'


  /devices/{name}:
    put:
      #operationId: api.devices.put
      parameters:
        - in: body
          name: name
          required: true
          schema:
            $ref: '#/definitions/DeviceRegistration'
        - in: path
          name: name
          required: true
          type: string


      responses:
        '200':
          description: 'Update a device by ID'
    delete:
      parameters:
        - in: path
          name: name
          required: true
          type: string
          enum: ["ZigBeeIPE", "MemsIPE"]
      responses:
        '204':
          description: 'Delete a device by device name'
    get:
      parameters:
        - in: path
          name: name
          required: true
          type: string
          enum: ["ZigBeeIPE", "MemsIPE"]
      responses:
        '200':
          description: 'Fetch a device by ID'
          schema:
            $ref: '#/definitions/Device'
definitions:
  DeviceRegistration:
    type: object
    properties:
      name:
       type: string
       example: "MemsIPE"

      device:
       $ref: '#/definitions/Device'


  Device:
    type: object
    properties:
      #name:
      # type: string
       #example: "MemsIPE"

      mems:
        $ref: '#/definitions/Mems'
#      zigbee:
#         $ref: '#/definitions/Zigbee'
      registered:
        type: string
        format: date-time


  Mems:
    type: object
    properties:
      x:
       type: object

      y:
       type: object
      z:
       type: object

#  Zigbee:
#    type: object
#    properties:
#      temperature:
#          type: object
#      brightness:
#          type: object
#      pressure:
#          type: object
#      movement:
#         type: object
#      humidity:
#          type: object


