swagger: "2.0"

info:
  title: "{{title}}"
  version: "0.0.5"

basePath: /eds

paths:
  /devices:
    get:
      #operationId: api.devices.get
      parameters:
       - in: query
         name: name
         type: string
         enum: ["ZigBeeIPE", "MemsIPE"]
         description: "Enter sensor device name here."
         #required: true
       #- in: query
        # name: id
       #  type: string
        # enum: ["MEMS01", "ZBS122S000000"]
        # example: MEMS01
        # description: "Enter sensor device ID here."
         #required: true
      responses:
        '200':
          description: 'Fetch a list of devices'
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
   # post:
    #  operationId: api.devices.post
     # parameters:
      #  - in: body
       #   name: name
        #  required: true
         # schema:
          #  $ref: '#/definitions/DeviceRegistration'
      #responses:
       # '201':
        #  description: 'List of device'


  /devices/{name}:
    put:
      #operationId: api.devices.put
      parameters:
        - in: body
          name: name
          required: true
          schema:
            $ref: '#/definitions/Device'
        - in: path
          name: name
          required: true
          type: string


      responses:
        '200':
          description: 'Update a device by ID'
    delete:
      parameters:
        - in: path
          name: name
          required: true
          type: string
          enum: ["ZigBeeIPE", "MemsIPE"]
      responses:
        '204':
          description: 'Delete a device by device name'
    get:
      parameters:
        - in: path
          name: name
          required: true
          type: string
          enum: ["ZigBeeIPE", "MemsIPE"]
      responses:
        '200':
          description: 'Fetch a device by ID'
          schema:
            $ref: '#/definitions/Device'
definitions:
  DeviceRegistration:
    type: object
    properties:
      name:
       type: string
       example: "MemsIPE"

      device:
       $ref: '#/definitions/Device'


  Device:
    type: object
    properties:
      #name:
      # type: string
       #example: "MemsIPE"

      mems:
        $ref: '#/definitions/Mems'
#      zigbee:
#         $ref: '#/definitions/Zigbee'
      registered:
        type: string
        format: date-time


  Mems:
    type: object
    properties:
        x:
          $ref: '#/definitions/X'
        y:
          $ref: '#/definitions/Y'
        z:
          $ref: '#/definitions/Z'
  X:
      type: object
      properties:
        bn:
          type: string
          example: "urn:dev1:memsipe"
          description: "basename of the mems sensor"

        u:
          type: string
          example: "g"
        v:
          type: number
          format: float
        t:
          type: string
          format: date-time
          description: the timestamp when the brightness was measured
        n:
          type: string
          example: "x"

        lbl:
          type: string
          example: "openmtc:sensor_data"
      description: ok


  Y:
      type: object
      properties:
        bn:
          type: string
          example: "urn:dev1:memsipe"
          description: "basename of the mems sensor"

        u:
          type: string
          example: "g"
        v:
          type: number
          format: float
        t:
          type: string
          format: date-time
          description: the timestamp when the brightness was measured
        n:
          type: string
          example: "y"

        lbl:
          type: string
          example: "openmtc:sensor_data"
      description: ok

  Z:
      type: object
      properties:
        bn:
          type: string
          example: "urn:dev1:memsipe"
          description: "basename of the mems sensor"

        u:
          type: string
          example: "g"
        v:
          type: number
          format: float
        t:
          type: string
          format: date-time
          description: the timestamp when the brightness was measured
        n:
          type: string
          example: "z"

        lbl:
          type: string
          example: "openmtc:sensor_data"
      description: ok


#  Zigbee:
#    type: object
#    properties:
#      temperature:
#          type: object
#      brightness:
#          type: object
#      pressure:
#          type: object
#      movement:
#         type: object
#      humidity:
#          type: object


