swagger: "2.0"

info:
  title: "{{title}}"
  version: "0.5.0"

basePath: /eds

paths:
  /devices:
    get:
      parameters:
       - in: query
         name: device
         type: string
         enum: ["Zigbee", "Mems"]
         description: "Enter sensor device name here."
         required: true
       - in: query
         name: id
         type: string
         enum: ["ZBS122S000001", "ZBS122S000000"]
         description: "Enter sensor device ID here."
         required: true
      responses:
        '200':
          description: 'Fetch a list of devices'
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
    post:
      parameters:
        - in: body
          name: device
          required: true
          schema:
            $ref: '#/definitions/DeviceRegistration'
      responses:
        '201':
          description: 'Register a new device'


  '/devices/{id}':
    put:
      parameters:
        - in: body
          name: device
          required: true
          schema:
            $ref: '#/definitions/Device'
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: 'Update a device by ID'
    delete:
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '204':
          description: 'Delete a device by ID'
    get:
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: 'Fetch a device by ID'
          schema:
            $ref: '#/definitions/Device'

definitions:
  DeviceRegistration:
    type: object
    properties:
      name:
       type: string
       example: "zigbee"
      id:
       type: string
       example: "ZBS122S000001"
  Device:
    type: object
    properties:
      name: { type: string }
      id:
        type: string
        format: string
      registered:
        type: string
        format: date-time
